name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create archive with makefile.d
        run: |
          tar -czf makefile.d.tar.gz makefile.d

      - name: Create release
        run: |
          gh release create ${{github.ref_name}} --generate-notes makefile.d.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
