name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Release
        run: |
          TOKEN=${{ secrets.GITHUB_TOKEN }} CROSS_TOKEN=${{secrets.GH_CROSS_TOKEN}} .github/workflows/release.sh ${{ github.ref_name }}